services:
#  app:
#    build:
#      context: .
#      dockerfile:  docker/Dockerfile
#    container_name: brixo-ifsc-app
#    env_file: .env
#    ports:
#      - "3000:3000"
#    depends_on:
#      - mongo
#      - redis
  mongo:
    image: mongo:7
    container_name: brixo-ifsc-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  redis:
    image: redis:7
    container_name: brixo-ifsc-redis
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    ports:
      - "6379:6379"
volumes:
  mongo_data:
